#+TITLE: K-means in Stock Market Modeling
#+AUTHOR: HuChen

* Abstract
  
  Stock market has traditionally been considered a very complex system which make it's
  difficult to describe or predict. Nevertheless, it's a reflection of humanity and somewhat
  make it's possible to do research and prediction.
  
  In this paper, we'll try to do clustering of China's stock market to check if there exists
  some repetitive patterns. The basic idea of clustering is that
  history will replay and similar movement of stock price can be used to predict the future.
  Fortunately, a back-test of our trading strategy which developed from clustering results
  suggest it's a effective or in other words, a clustering method can be used to study our
  stock market. With such conclusion, traditional behavior finance may be application in
  clustering results which with much less noise.

* Introduction

  Since the entry of WTO, China has been playing more and more import role in World's
  economy system due to its exploding growth. Along with the income of money from worldwide, 
  advanced ideas such as quantitative investment has also been introduced. 
  
  Because of strictly disciple and decisive entry and exist point, quantitative investment
  can effectively avoid weakness of human nature and help investors do more reasonable 
  decisions. It has been more and more welcome in financial region. 

  In financial market, there exist mainly two kinds of investors which are fundamental analysts
  and technical analysts. Fundamental analysts examine earnings, dividends, assets, quality, 
  ratio, new products, research and the like while technicians employ many methods, tools and 
  techniques as well, trying to predict the future evolution of stock prices. For technicians,
  they believe the replay of history and some of them did earn money. Some techniques have
  been introduced from those who earned money, such as Turtle Trading Rules, Bollinger Bands,
  KDJ and so on.

  Nevertheless, with more and more people use the limited techniques, it's been difficult to 
  earn money as old days. Recently, with the development of Computer Science, machine learning
  has been hot in a variety of aspects including financial market. Despite those complex algorithms,
  in this paper, we just use a simple clustering method which is well-known as K-means method to
  study China's stock market. 

  A very important reason why we use such simple algorithm is the limitation of data scale. 
  Due to the short history, there may not be enough data to feed such as neural network. For a 
  long time, the special constitution of China's investors make it hard to simply apply the 
  foreign financial data. On the other side, our study suggest a lot even with such simple
  clustering method.

** Quantitative Investment 
   
** Introduction of K-means
   
* Modeling Stock Market Using K-means

** Basic Idea

** Method

** Test

* Discussion
